name: transcripts
description: Tools for building webpages of linked Netflix transcripts

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  xml: ^5.0.2

publish_to: none

executables:
  build: 